### ISSUE TITLE
Navigation for 404 error page

### ISSUE THREAD

**Issue by satyam73** [Real-Dev-Squad/members-site#11]
While I was surfing the website I found out one issue which needs to be addressed that is in the 404 error page there is no navigation for the user to navigate to the other pages.

**Solution:**

We can add the navigation menu to navigate the user to the other screen if route doesn't exist.

**Image for reference :** 
![image](https://user-images.githubusercontent.com/85296770/209359606-ae269c1f-e184-40ad-a4f4-717f48a9af7d.png)

**Comment by satyam73** [comment]
Hello @vinayak-trivedi you can assign this issue to me.

**Comment by vinayak-trivedi** [comment]
this is done
