### ISSUE TITLE
Add NEXT_PUBLIC_TASK_BASE_URL to .env for staging

### ISSUE THREAD

**Issue by ashifkhn** [Real-Dev-Squad/members-site#161]
### Issue Description

Description:

We need to configure the environment variable NEXT_PUBLIC_TASK_BASE_URL for the staging environment. This URL is used for the onClick navigation functionality to navigate to task details.

Details:

Environment Variable: NEXT_PUBLIC_TASK_BASE_URL
Value: https://staging-status.realdevsquad.com
Purpose: This URL will be used in the staging environment to ensure that the onClick navigation properly directs users to the correct task details page.

NEXT_PUBLIC_TASK_BASE_URL=https://staging-status.realdevsquad.com

### Steps to Reproduce
1. 
2. 

### Severity/Priority
 - [ ] Critical
 - [x] High
 - [ ] Medium
 - [ ] Low

### Additional Information

Impact:

This change is crucial for ensuring that task detail navigation functions correctly in the staging environment. Without this configuration, navigation might not work as expected during testing.

Additional Notes:

Please ensure that this variable is not included in the production .env file to avoid any potential conflicts or security issues.

### Checklist

- [x] I have read and followed the project's code of conduct.
- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand and reproduce the issue.
- [ ] I am willing to contribute to the resolution of this issue.

**Comment by prakashchoudhary07** [comment]
Hey, why are we adding this?

**Comment by ashifkhn** [comment]
> Hey, why are we adding this?

we needed the base url to navigate to task detail page. added in const as suggested by @iamitprakash .
