### ISSUE TITLE
Navbar HOC

### ISSUE THREAD

**Issue by vinayak-trivedi** [Real-Dev-Squad/members-site#18]
- create a Higher Order Component of Navbar which will be used in different page
- Refer to the following image for reference:
![image](https://user-images.githubusercontent.com/90315175/214867773-c98783e6-5393-40cf-b4c3-0dba824b9652.png)

**Comment by shubhamsigdar1** [comment]
I want this task

**Comment by shubhamsigdar1** [comment]
ETA by 11.02.2023

**Comment by codewithkushagra** [comment]
I want to work on this issue

**Comment by codewithkushagra** [comment]
ETA by 19th Feb, 10:00 PM
