### ISSUE TITLE
Members individual page [member info section]

### ISSUE THREAD

**Issue by vinayak-trivedi** [Real-Dev-Squad/members-site#19]
- we have an individual page for each member of real dev squad which is used to showcase all the contributions of a member of RDS, make the info section of that user on that page

![image](https://user-images.githubusercontent.com/90315175/214870132-1f1e4db6-c879-4165-9b92-cc11eee626a2.png)

go to [member page](https://members.realdevsquad.com/vinayak) to see how it looks

**Comment by kshitij430** [comment]
Please assign it to me.

**Comment by kshitij430** [comment]
ETA by 07/02/2022.

**Comment by vinayak-trivedi** [comment]
this is done, so closing it
