### ISSUE TITLE
Members individual page [contribution section]

### ISSUE THREAD

**Issue by vinayak-trivedi** [Real-Dev-Squad/members-site#20]
- we have an individual page for each member of real dev squad which is used to showcase all the contributions of a member of RDS, make contribution section of that page

![image](https://user-images.githubusercontent.com/90315175/214870983-516a89e4-39bd-4a31-a396-e5d262acc990.png)

[check this page](https://members.realdevsquad.com/vinayak) to see it live

**Comment by ranitasahaa1230** [comment]
I want to work on this issue. Could you please assign this to me @vinayak-trivedi?

**Comment by ranitasahaa1230** [comment]
ETA by 14/02/2023

**Comment by codewithkushagra** [comment]
I want to work on this issue @vinayak-trivedi
