### ISSUE TITLE
Members site main page [ New members section ]

### ISSUE THREAD

**Issue by vinayak-trivedi** [Real-Dev-Squad/members-site#22]
- our main page showcases all the members and users of RDS who are not yet members
- it should contain two sections: Real Dev Squad Members, and new users
- make the New user section of that

check [members site](https://members.realdevsquad.com) to see how it is currently looking

**Comment by sahsisunny** [comment]
**ETA** - 12 Feb 2023

**Comment by sahsisunny** [comment]
feature added in #28 PR
