### ISSUE TITLE
rtk query setup for all the queries and mutations

### ISSUE THREAD

**Issue by vinayak-trivedi** [Real-Dev-Squad/members-site#25]
- setup store for all the queries and mutations that we have

### Queries

- getMembers: `base_url/members`
- getMembersData: `base_url/users/:rds_user_id`
- getContribution: `base_url/contributions/:rds_user_id`
- getUserActiveTask: `base_url/tasks/:rds_user_id/?status=active`

### Mutations

- updateMemberRole:  `base_url}/members/moveToMembers/:rds_user_id
- archiveMember: `base_url/members/archiveMembers/:rds_user_id`
- updateTaskStatus: `base_url/tasks/:task_id

- we need to use next redux wrapper to use SSG SSR in our apps

**Comment by satyam73** [comment]
ETA - 10 Feb 2023
