### ISSUE TITLE
add eslint rules to the project

### ISSUE THREAD

**Issue by vinayak-trivedi** [Real-Dev-Squad/members-site#4]
- add some eslint rules to the project
- refer the [official docs](https://eslint.org/docs/latest/rules/) for help

**Comment by kush-x7** [comment]
Next js comes with basic linting. You can check this -> https://nextjs.org/docs/basic-features/eslint#eslint-plugin
and if we still need to add some linting then what rules we will be referring to? because the official docs have so many rules.

**Comment by vinayak-trivedi** [comment]
> Next js comes with basic linting. You can check this -> https://nextjs.org/docs/basic-features/eslint#eslint-plugin and if we still need to add some linting then what rules we will be referring to? because the official docs have so many rules.

sure, I will add the rules that I want to add
